name: very_commons
description: Common classes for very libraries
version: 0.1.0
repository: https://github.com/akurnaz/very_commons

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
