name: very_commons
description: Common classes for very libraries
version: 0.1.0
repository: https://github.com/akurnaz/very_commons

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
